name: salesforce_transformations
version: 1.0.0
config-version: 2

profile: salesforce_transformations

model-paths: ["models"]
test-paths: ["tests"]
macro-paths: ["macros"]

clean-targets:
  - target
  - dbt_packages

models:
  salesforce_transformations:
    staging:
      +schema: staging
      +materialized: view
      +tags: ["salesforce", "staging"]
    intermediate:
      +schema: intermediate
      +materialized: incremental
      +tags: ["salesforce", "intermediate"]
      +incremental_strategy: delete+insert
      +on_schema_change: sync_all_columns
    marts:
      +schema: marts
      +materialized: table
      +tags: ["salesforce", "marts"]
