#!/bin/bash

if ! command -v cz >/dev/null && [ "$DEVPOD" = "true" ]; then
    git config --global push.autoSetupRemote true
    git config --global --add safe.directory /workspaces/"$DEVPOD_WORKSPACE_ID"/
    uv tool install commitizen
    pre-commit install
    pre-commit install --hook-type commit-msg
fi