select
    "Id" as account_id,
    "Name" as account_name,
    "AccountNumber" as account_number,
    "Type" as account_type,
    "Industry" as industry,
    {{ safe_numeric('"AnnualRevenue"') }} as annual_revenue,
    {{ safe_integer('"NumberOfEmployees"') }} as number_of_employees,
    "Website" as website,
    "Phone" as phone,
    "OwnerId" as owner_id,
    "ParentId" as parent_account_id,
    "BillingCity" as billing_city,
    "BillingState" as billing_state,
    "BillingCountry" as billing_country,
    "ShippingCity" as shipping_city,
    "ShippingState" as shipping_state,
    "ShippingCountry" as shipping_country,
    {{ safe_boolean('"IsDeleted"') }} as is_deleted,
    {{ safe_boolean('"Active__c"') }} as is_active,
    {{ safe_integer('"NumberofLocations__c"') }} as number_of_locations,
    to_date(nullif("SLAExpirationDate__c", ''), 'YYYY-MM-DD') as sla_expiration_date,
    nullif("SystemModstamp", '')::timestamptz as systemmodstamp,
    extracted_at,
    dag_run_id
from raw_salesforce.accounts
